services:
  nextcloud-mariadb:
    image: mariadb:10.7.3
    container_name: nextcloud-mariadb
    restart: always
    volumes:
      - "./nextcloud-mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  nextcloud-redis:
    image: redis:6.2.6
    container_name: nextcloud-redis
    restart: always
    volumes:
      - "./nextcloud-redis:/var/lib/redis"

  nextcloud:
    image: nextcloud:22.2.6-apache
    container_name: nextcloud
    restart: always
    volumes:
      - "./nextcloud:/var/www/html"
    environment:
      NEXTCLOUD_DOMAIN_NAME: nextcloud.moxthos.art
      NEXTCLOUD_TRUSTED_DOMAIN: nextcloud.moxthos.art
      MYSQL_HOST: nextcloud-mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: password
      REDIS_HOST: nextcloud-redis
      TRUSTED_PROXIES: traefik
      OVERWRITEHOST: nextcloud.moxthos.art
      OVERWRITEPROTOCOL: https
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.moxthos.art`)"
      - "traefik.http.routers.nextcloud.entrypoints=web-secured"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
